arduino:
  VID: 0x2341
  PID: 0x0042
  BITRATE: 115200

multimeter:
  VID: 0x1AB1
  PID: 0x09C4

can:
  VID: 0x0403
  PID: 0xECD9

paths:
  product_base: "C:/Users/Lab/Documents/InternalProjects/SteeringCalibration"

