# -*- coding: utf-8 -*-
#==============================================================================
#                  Copyright(c) 1997-2021 by miControl(R). All rights reserved.
#
# System   : mcTools V1.12.09.00
# Company  : miControl(R)
#
# Date Time: 08.11.2021 15:31:14
#==============================================================================
# Description: This file was generated by mcTools
#==============================================================================

def InitPar (d):

   new_node_id = 5                                # new NodeId
   d.SdoWr(0x2000, 0x01, 0x6E657277)               # write enable
   d.SdoWr(0x2000, 0x02, new_node_id, timeout=500) # set new NodeId
   #d.SdoWr(0x2000, 0x01, 0x6E657277)               # write enable
   #d.SdoWr(0x2000, 0x03, 1 , timeout=500)     # set baud rate 500kbit/s


   d.SdoWr(0x3004, 0x00, 0)           # DEV_Enable - Disable
   d.SdoWr(0x3000, 0x00, 0x1)         # DEV_Cmd - Clear error
   d.SdoWr(0x3000, 0x00, 0x82)        # DEV_Cmd - Default parameter

   d.SdoWr(0x3003, 0x00, 7)           # DEV_Mode
   #d.SdoWr(0x3708, 0x00, 2)           # Position_Mode_Modulo_positioning(new)
   #d.SdoWr(0x37C8, 0x00, 0)           # Modulo_Method_Shortpath(new)
   #d.SdoWr(0x37C9, 0x00, 4097)        # Modulo_Value(new)
   #d.SdoWr(0x3765, 0x00, 2048)        # Position_origin(new)

   d.SdoWr(0x3200, 0x00, 0)           # CURR_DesiredValue

   d.SdoWr(0x3210, 0x00, 8)           # CURR_Kp
   d.SdoWr(0x3211, 0x00, 1)           # CURR_Ki

   d.SdoWr(0x3221, 0x00, 5000)        # CURR_LimitMaxPos
   d.SdoWr(0x3223, 0x00, 5000)        # CURR_LimitMaxNeg
   d.SdoWr(0x3224, 0x01, 120000)      # CURR_DynLimitPeak
   d.SdoWr(0x3224, 0x02, 120000)      # CURR_DynLimitCont

   d.SdoWr(0x3300, 0x00, 1500)        # VEL_DesiredValue

   d.SdoWr(0x3310, 0x00, 5)           # VEL_Kp
   d.SdoWr(0x3311, 0x00, 1)           # VEL_Ki
   d.SdoWr(0x3314, 0x00, 1000)        # VEL_Kvff

   d.SdoWr(0x3341, 0x00, 200)         # VEL_Acc_dT
   d.SdoWr(0x3343, 0x00, 200)         # VEL_Dec_dT

   d.SdoWr(0x3350, 0x00, 0x97A)       # VEL_Feedback

   d.SdoWr(0x3500, 0x00, 0)           # SVEL_DesiredValue

   d.SdoWr(0x3510, 0x00, 200)         # SVEL_Kp

   d.SdoWr(0x3550, 0x00, 0x94A)       # SVEL_Feedback

   d.SdoWr(0x3732, 0x00, 4294967295)  # POS_FollowingErrorWindow

   d.SdoWr(0x3900, 0x00, 1)           # MOTOR_Type
   d.SdoWr(0x3901, 0x00, 3000)        # MOTOR_Nn
   d.SdoWr(0x3902, 0x00, 24000)       # MOTOR_Un

   d.SdoWr(0x3910, 0x00, 20)          # MOTOR_PolN
   d.SdoWr(0x3911, 0x00, 0)           # MOTOR_Polarity

   d.SdoWr(0x3913, 0x07, 0)           # MOTOR_Commutation_Polarity
   d.SdoWr(0x3913, 0x84, 0x94A)       # PAR_3913.84h

   d.SdoWr(0x3962, 0x00, 34)          # MOTOR_ENC_Resolution

   d.SdoWr(0x3970, 0x00, 1)           # MOTOR_ENC_SSI_Enable
   d.SdoWr(0x3971, 0x01, 12)          # MOTOR_ENC_SSI_SignificantBits
   d.SdoWr(0x3971, 0x02, 12)          # MOTOR_ENC_SSI_Bits
   d.SdoWr(0x3972, 0x00, 34)          # MOTOR_ENC_SSI_Resolution

   d.SdoWr(0x3940, 0x00, 2)           # MOTOR_HALL_Type
   d.SdoWr(0x3946, 0x08, 21930)       # MOTOR_HALL_Tuning_WrEnable
   d.SdoWr(0x3946, 0x00, 1)           # MOTOR_HALL_Tuning_Sector0
   d.SdoWr(0x3946, 0x01, 5)           # MOTOR_HALL_Tuning_Sector1
   d.SdoWr(0x3946, 0x02, 4)           # MOTOR_HALL_Tuning_Sector2
   d.SdoWr(0x3946, 0x03, 6)           # MOTOR_HALL_Tuning_Sector3
   d.SdoWr(0x3946, 0x04, 2)           # MOTOR_HALL_Tuning_Sector4
   d.SdoWr(0x3946, 0x05, 3)           # MOTOR_HALL_Tuning_Sector5

   d.SdoWr(0x3971, 0x00, 1)           # MOTOR_ENC_SSI_Code
   #d.SdoWr(0x3762, 0x00, 0)           # Set_Absolute_Position_Zero(new)
   #d.SdoWr(0x3970, 0x08, 0x65766173)  # Save_Absolute_Encoder_Value(new)

   d.SdoWr(0x3B00, 0x00, 2)           # FCT_Control

   d.SdoWr(0x3B12, 0x00, 0xAC)        # FCT_PosDimIndex

   d.SdoWr(0x3000, 0x00, 0x80)        # DEV_Cmd - Store parameters

#------------------------------------------------------------------------------
if __name__ == '__main__':
   from mc.dsa import *

   d = Dsa(2)

   InitPar(d)
   print("code is executed")
